spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ms-email-ms
    username: postgres-email
    password: postgres-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqps://qtnittkk:YAy2EkzANWV_Hgi0zJR2g7h75v5F6B2B@campbell.lmq.cloudamqp.com/qtnittkk
    username: qtnittkk
    password: YAy2EkzANWV_Hgi0zJR2g7h75v5F6B2B
    virtual-host: qtnittkk

server:
  port: 8080
