version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ms-email-db
    environment:
      POSTGRES_DB: ms-email-ms
      POSTGRES_USER: postgres-email
      POSTGRES_PASSWORD: postgres-password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

